name: k_chart
description: A Flutter K Chart.
version: 0.7.1
homepage: https://github.com/mafanwei/k_chart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  common_utils: ^2.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
